export const User = [
  {
    name: 'visha Foundation',
    email: 'vishva.dadhaniya@viitor.cloud',
    password: 'Test@123',
    emailVerified: true,
    userType: 'Admin',
    acceptTerms: true,
    phoneNumber: '8788270435',
  },
  {
    name: 'visha Foundation',
    email: 'vishva.dadhaniya1@viitor.cloud',
    password: 'Test@123',
    emailVerified: true,
    userType: 'User',
    acceptTerms: true,
    phoneNumber: '8788270435',
  },
  {
    name: 'visha Foundation',
    email: 'vishva.dadhaniya2@viitor.cloud',
    password: 'Test@123',
    emailVerified: true,
    userType: 'User',
    acceptTerms: true,
    phoneNumber: '8788270435',
  },
  {
    name: 'visha Foundation',
    email: 'vishva.dadhaniya3@viitor.cloud',
    password: 'Test@123',
    emailVerified: true,
    userType: 'User',
    acceptTerms: true,
    phoneNumber: '8788270435',
  },
  {
    name: 'visha Foundation',
    email: 'vishva.dadhaniya4@viitor.cloud',
    password: 'Test@123',
    emailVerified: true,
    userType: 'User',
    acceptTerms: true,
    phoneNumber: '8788270435',
  },
  {
    name: 'visha Foundation',
    email: 'vishva.dadhaniya5@viitor.cloud',
    password: 'Test@123',
    emailVerified: true,
    userType: 'User',
    acceptTerms: true,
    phoneNumber: '8788270435',
  },
];
